server:
  port: 10010
spring:
  application:
    name: itcast-zuul
zuul:
  routes:
    service-provider: #\u8DEF\u7531\u540D\u79F0\uFF0C\u53EF\u4EE5\u968F\u4FBF\u5199 \u4E60\u60EF\u4E0A\u662F\u670D\u52A1\u540D
      path: /service-provider/**
        url: http://localhost:8081
